### PR TITLE
feat: add reusable  CD workflow

### PR DESCRIPTION
**Pull request by vmaerten**
CD workflow is almost the same for all repo
When we need to do a change (for exemple update github action version, add release, etc) we need to do in every repo
The goal is to define the CD here, and use it in multiple repo
I already did it in the App to test it : https://github.com/pbstck/app/blob/main/.github/workflows/CD.yaml

It's a proposal, WDYT ?
If you agree on that, I'll do others

### CODE REVIEW

**Review by ridwan-b — COMMENTED** [review]
I do like the idea of merging common code to simplify future updates.
But, I also think that it can be kind of risky because this is the CD part which is, in my opinion, difficult to test.
I'm sure that it will help us save a lot of time but we'll need to be really careful before merging any changes on it.

**Review by ridwan-b — APPROVED** [review]

**Comment by vmaerten** [comment]
> I do like the idea of merging common code to simplify future updates. But, I also think that it can be kind of risky because this is the CD part which is, in my opinion, difficult to test. I'm sure that it will help us save a lot of time but we'll need to be really careful before merging any changes on it.

I agree with you! We need to test it in a branch before and be careful on what we change here

**Review by bvionpubstack — APPROVED** [review]

**Review by ildede — APPROVED** [review]
If we have a common way of doing this, it is good to mutualize it!

The only concern I have at the moment is that, as far as I know, kleanads.js does not utilize the same tag convention and `get_stage` would not work.

But I hope people with more knowledge of the subject will say something 😅

**Comment by vmaerten** [comment]
We can update get_stage to match kleanads.js if needed
The goal is to mutualize all projects we can, if kleanads does not fit, it's ok, It should not block this IHMO

**Review by cforycki — APPROVED** [review]
LGTM

And for kleanads.js, it needs to be discussed, because we tried to have `dev/beta/prod` env and an uniform way of tagging. We already should have had a brainstorming about kleanads.js if needs were not the same and understand the implication of these changes, but it has not been done this way unfortunately.

**Review by afigoureux-pbstck — APPROVED** [review]

**Review by erwanncloarec — APPROVED** [review]

**Pull request merged**
