### PR TITLE
Feat: add shared key to identify rust cache 

### PR DESCRIPTION
**Pull request by ridwan-b**
Here is a proposal to "optimize" the way rust cache is saved/restored.
Actually, every rust cache are named like this : **v0-rust-0.2.2-_JOB_NAME_-_HASH_**
So every "rust" job needs to have his specific cache.

The rust-cache action has a property **shared-key** which if it's set name the cache as **v0-rust-_SHARED_KEY_-_HASH_**

So I added a new param to setup-rust action to fill shared-key param, and set a default value to repo name if no value is given.

[see doc](https://github.com/Swatinem/rust-cache/tree/v2)

Question : do we want to keep the cross-version into cache name ? if yes, still need to work a bit on this PR

### CODE REVIEW

**Review by afigoureux-pbstck — APPROVED** [review]

**Comment by cforycki** [comment]
I already tried that, but it was not working so I add to revert it.

Because the key is always the same, it doesn't cache after the build, so you win some time for the dependencies, but have to rebuild everything from scratch every time.

At least, that what I experienced.

**Comment by vmaerten** [comment]
Do you have a repo where you tested it ?
From what I remember, It does not work well in our case :( but maybe I'm wrong or they changed the behavior

**Comment by ridwan-b** [comment]
yes you're right guys. We are actually testing on a specific branch of kleanads-server and we see that the build time is increasing... We are about to test more stuff with how cargo firstly fetch dependencies.

I blocked this PR while test aren't OK

**Comment by vmaerten** [comment]
Hello
What is the status of this PR? Do you want to work on it? Or should we close it for now?

**Comment by cforycki** [comment]
Stale PR, restore branch and reopen if needed

**Comment by ridwan-b** [comment]
Yes I wanted to close it, thanks guys :)

**Pull request closed without merging**
